### ISSUE TITLE
Fail creating questionnaire - "questionTagUudis" not recognized as parameter

### ISSUE THREAD

**Issue by aleolivo** [ds-wizard/dsw-sdk#50]
Probably you are already working on it and I know, the version 3.8 has just been released, but maybe this feedback could be useful (I don't know).

**The problem**
Fail creating questionnaire, "questionTagUudis" is not recognized as a parameter (more on "A little bit of debugging" section)

**How to reproduce the error**
Start docker local deployment example version 3.8 and import a km

After this call:
``` python
dsw_sdk = DataStewardshipWizardSDK(
    api_url='http://localhost:3000',
    email='albert.einstein@example.com',
    password='password',
)
params = {
    "packageId": "myorg:dmp:0.0.1",
    "questionTagUuids": [],
    "visibility": "PrivateQuestionnaire",
    "name": "test-dmp",
    "sharing": "RestrictedQuestionnaire"
}
dsw_sdk.questionnaires.create_questionnaire(**params)
```
The server reply with this error:
``` 
dsw_sdk.http_client.interface.BadRequestError: [400] Problem in deserialization of JSON (/questionnaires)
```
**A little bit of debugging**
Instead of the "questionTagUuids" parameter the "tagUuids" parameter is sent in the http post request "/questionnaires"

It seems that in the following piece of code the "questionTagUuids" is not added as attribute in the `AttributesMixin` object because it is not in `self.attr_names` 

In `attributes.py` (line 191):
``` python
# Set all attributes passed as kwargs
for attr_name, attr in kwargs.items():
    if to_snake_case(attr_name) in self.attr_names:
    setattr(self, to_snake_case(attr_name), attr)
```

I'm trying to modify `questionnaire.py` (line 69) with an alias but probably is not the right way

**Comment by drahoja9** [comment]
Hey Alessandro,

thanks for reporting! The SDK is currently not up to date with the rest of the DSW stack (latest compatible version is 3.6).
I will look into it, the upgrade should be ready soon. :)

**Comment by drahoja9** [comment]
I've updated the SDK to correspond to the latest version of the DSW and deployed it on [PyPI](https://pypi.org/project/dsw-sdk/).
I have also tested the creation of a questionnaire according to your steps and everything seems alright. Please, feel free to test it out and issue more tickets if anything is not to your liking. :)

**Comment by alessandro-olivo** [comment]
Great! Thanks so much for the quick responses and the quick code update!
I'll use this module a bit, so in case of some strange behaviour I'll get back to you! Thanks :)
