### ISSUE TITLE
KM/package can use `latest` as a version

### ISSUE THREAD

**Issue by drahoja9** [ds-wizard/dsw-sdk#7]
When working with packages (knowledge models), you can use `latest` keyword instead of a specific version, e.g. `dsw:root:latest` instead of `dsw:root:2.3.0`.

New in version 3.0.0

**Comment by MarekSuchanek** [comment]
Checked in the code, it does not affect anything at the moment - IDs (including version) are entered only as strings, no validation is done in this regard.
